name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: 
        |
        wget https://samples-files.com/samples/images/bmp/480-360-sample.bmp
        php -r '$fileInfo = new finfo(); echo $fileInfo->file("480-360-sample.bmp", FILEINFO_MIME_TYPE);'

